
environment:
  name: "uat"
  environmentName: "uat"
  replicas:
    quantity: 1
  resources:
    xmx: 700M
    xms: 200M
    requests:
      memory: "800Mi"
      cpu: "100m"
    limits:
      memory: "2Gi"
      cpu: "2"

spring:
  application:
    name: trading-specification-service

image:
  name: "tradingSpecificationApi"
  tag: "latest"
  debug:
    enabled: false
    port: 1234

ingress:
  host: trading.signal.specification

application:
  name: trading-service